/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra4.ui;

import progra4.Paciente;
import progra4.ui.GuiExpediente;
import progra4.Pantalla;

/**
 *
 * @author yoorda
 */
public class GuiExpediente extends javax.swing.JFrame {

    Paciente paciente = new Paciente();

    public GuiExpediente() {
        initComponents();
        imprimirselect();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void imprimirselect() {
        int itemCount = jComboBoxidE.getItemCount();
        for (int i = 0; i < itemCount; i++) {
            jComboBoxidE.removeItemAt(0);
        }
        String data = "idPaciente";
        String condicion = null;
        String order = "idPaciente->ASC";
        String[][] resultado = paciente.imprimir(data, condicion, order);
        for (int x = 0; x < resultado.length; x++) {
            jComboBoxidE.addItem(resultado[x][0]);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNombreExpediente = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNExpediente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldFechaExpediente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTratamiento = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAlergias = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaAntecedentes = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaComentarios = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldOtros = new javax.swing.JTextField();
        jComboBoxidE = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(620, 470));
        setMinimumSize(new java.awt.Dimension(620, 470));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(620, 470));
        getContentPane().setLayout(null);

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Buscar-01.png"))); // NOI18N
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar);
        jButtonBuscar.setBounds(570, 130, 40, 40);

        jLabel3.setFont(new java.awt.Font("Dolce Vita Heavy", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Expediente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 250, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Identificación");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 90, 90, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nombre");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 120, 60, 15);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 400, 20, 20);
        getContentPane().add(jTextFieldNombreExpediente);
        jTextFieldNombreExpediente.setBounds(110, 120, 150, 20);

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar-01.png"))); // NOI18N
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar);
        jButtonGuardar.setBounds(570, 90, 40, 40);

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar4-01.png"))); // NOI18N
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir);
        jButtonSalir.setBounds(570, 10, 40, 40);

        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menú2-01.png"))); // NOI18N
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMenu);
        jButtonMenu.setBounds(570, 50, 40, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Numero de Expediente");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 90, 150, 15);

        jTextFieldNExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNExpedienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNExpediente);
        jTextFieldNExpediente.setBounds(420, 90, 140, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Fecha de Expediente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 120, 130, 14);

        jTextFieldFechaExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaExpedienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldFechaExpediente);
        jTextFieldFechaExpediente.setBounds(400, 120, 160, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tratamiento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 290, 90, 15);

        jTextAreaTratamiento.setColumns(20);
        jTextAreaTratamiento.setRows(5);
        jScrollPane1.setViewportView(jTextAreaTratamiento);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 310, 250, 100);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Alergias");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 160, 60, 15);

        jTextAreaAlergias.setColumns(20);
        jTextAreaAlergias.setRows(5);
        jTextAreaAlergias.setMaximumSize(new java.awt.Dimension(250, 100));
        jTextAreaAlergias.setMinimumSize(new java.awt.Dimension(250, 100));
        jScrollPane2.setViewportView(jTextAreaAlergias);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(310, 180, 250, 100);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Antecedentes");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 160, 90, 15);

        jTextAreaAntecedentes.setColumns(20);
        jTextAreaAntecedentes.setRows(5);
        jTextAreaAntecedentes.setMaximumSize(new java.awt.Dimension(250, 100));
        jTextAreaAntecedentes.setMinimumSize(new java.awt.Dimension(250, 100));
        jScrollPane3.setViewportView(jTextAreaAntecedentes);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(50, 180, 250, 100);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Comentarios");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 290, 80, 15);

        jTextAreaComentarios.setColumns(20);
        jTextAreaComentarios.setRows(5);
        jTextAreaComentarios.setMaximumSize(new java.awt.Dimension(250, 100));
        jTextAreaComentarios.setMinimumSize(new java.awt.Dimension(250, 100));
        jScrollPane4.setViewportView(jTextAreaComentarios);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(50, 310, 250, 100);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Otros");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 420, 40, 15);
        getContentPane().add(jTextFieldOtros);
        jTextFieldOtros.setBounds(90, 420, 470, 20);

        getContentPane().add(jComboBoxidE);
        jComboBoxidE.setBounds(140, 90, 120, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pantallas3-01.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 630, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed

        GuiMenu menu = new GuiMenu();
        menu.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed

        System.exit(0);//Cerrar la ventana
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldNExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNExpedienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNExpedienteActionPerformed

    private void jTextFieldFechaExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaExpedienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaExpedienteActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed

        GuiMenu menu = new GuiMenu();
        menu.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiExpediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxidE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaAlergias;
    private javax.swing.JTextArea jTextAreaAntecedentes;
    private javax.swing.JTextArea jTextAreaComentarios;
    private javax.swing.JTextArea jTextAreaTratamiento;
    private javax.swing.JTextField jTextFieldFechaExpediente;
    private javax.swing.JTextField jTextFieldNExpediente;
    private javax.swing.JTextField jTextFieldNombreExpediente;
    private javax.swing.JTextField jTextFieldOtros;
    // End of variables declaration//GEN-END:variables
}
