/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra4.ui;

/**
 *
 * @author yoorda
 */
public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiDoctor
     */
    public GuiMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonDoctor = new javax.swing.JButton();
        jButtonUsuario = new javax.swing.JButton();
        jButtonAsistente = new javax.swing.JButton();
        jButtonAgenda = new javax.swing.JButton();
        jButtonPaciente = new javax.swing.JButton();
        jButtonCita1 = new javax.swing.JButton();
        jButtonCita2 = new javax.swing.JButton();
        jButtonExpediente = new javax.swing.JButton();
        jButtonCita4 = new javax.swing.JButton();
        jButtonPaciente1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(590, 365));
        setMinimumSize(new java.awt.Dimension(590, 365));
        setName("FrameMenu"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(590, 365));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Dolce Vita Heavy", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MENÚ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 20, 150, 60);

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar4-01.png"))); // NOI18N
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir);
        jButtonSalir.setBounds(540, 10, 40, 40);

        jButtonDoctor.setText("Doctor");
        jButtonDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDoctor);
        jButtonDoctor.setBounds(30, 130, 100, 23);

        jButtonUsuario.setText("Usuario");
        jButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUsuario);
        jButtonUsuario.setBounds(30, 170, 100, 23);

        jButtonAsistente.setText("Asistente");
        jButtonAsistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsistenteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAsistente);
        jButtonAsistente.setBounds(30, 90, 100, 23);

        jButtonAgenda.setText("Agenda");
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgenda);
        jButtonAgenda.setBounds(180, 250, 120, 23);

        jButtonPaciente.setText("Pacientes");
        jButtonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPaciente);
        jButtonPaciente.setBounds(180, 210, 120, 23);

        jButtonCita1.setText("Permisos");
        jButtonCita1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCita1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCita1);
        jButtonCita1.setBounds(30, 210, 100, 23);

        jButtonCita2.setText("Pantalla");
        jButtonCita2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCita2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCita2);
        jButtonCita2.setBounds(180, 90, 120, 23);

        jButtonExpediente.setText("Expedientes");
        jButtonExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExpedienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExpediente);
        jButtonExpediente.setBounds(180, 130, 120, 23);

        jButtonCita4.setText("Especialidades");
        jButtonCita4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCita4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCita4);
        jButtonCita4.setBounds(180, 170, 120, 23);

        jButtonPaciente1.setText("Servicios");
        jButtonPaciente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaciente1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPaciente1);
        jButtonPaciente1.setBounds(30, 250, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clinica3-01.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPaciente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaciente1ActionPerformed
        GuiServicios servicios = new GuiServicios();
        servicios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPaciente1ActionPerformed

    private void jButtonCita4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCita4ActionPerformed
        GuiEspecialidades especialidades = new GuiEspecialidades();
        especialidades.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCita4ActionPerformed

    private void jButtonExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExpedienteActionPerformed

        GuiExpediente expediente = new GuiExpediente();
        expediente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonExpedienteActionPerformed

    private void jButtonCita2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCita2ActionPerformed

        GuiPantalla pantalla = new GuiPantalla();
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCita2ActionPerformed

    private void jButtonCita1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCita1ActionPerformed

        GuiPermisos permisos = new GuiPermisos();
        permisos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCita1ActionPerformed

    private void jButtonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacienteActionPerformed

        GuiPaciente paciente = new GuiPaciente();
        paciente.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPacienteActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed

        GuiAgenda citas = new GuiAgenda();
        citas.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jButtonAsistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsistenteActionPerformed

        GuiAsistente asistente = new GuiAsistente();
        asistente.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAsistenteActionPerformed

    private void jButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioActionPerformed

        GuiUsuario usuario = new GuiUsuario();
        usuario.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUsuarioActionPerformed

    private void jButtonDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoctorActionPerformed

        GuiDoctor doctor = new GuiDoctor();
        doctor.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDoctorActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed

        System.exit(0);//Cerrar la ventana
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonAsistente;
    private javax.swing.JButton jButtonCita1;
    private javax.swing.JButton jButtonCita2;
    private javax.swing.JButton jButtonCita4;
    private javax.swing.JButton jButtonDoctor;
    private javax.swing.JButton jButtonExpediente;
    private javax.swing.JButton jButtonPaciente;
    private javax.swing.JButton jButtonPaciente1;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
